eureka:
  client:
    register-with-eureka: yes
    fetch-registry: yes
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 8761

Spring:
  application:
    name: PREDICTION-NATIONALITY-WS



